name: C/C++ CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest 
        
        steps:
        - name: GOTO home
          run: cd $HOME && ls
        - name: INSTALL boost lib
          run: sudo apt-get install libboost-all-dev
        - name: INSTALL wx3.0
          run: sudo apt-get install wx3.0* libwxgtk3.0-dev
        - name: CLONE wxMathPlot and proj
          run: git clone https://github.com/mkarmona/wxMathPlot.git
        - name: CLONE 
          run:  git clone -b dev https://github.com/z4deepfz/SerialPort-Assistant.git
        - name: MAKE wxMathPlot
          run: ls && cd wxMathPlot && cmake -G "Unix Makefiles" && make -j2 && cd ..
        - name: LIST
          run: cd SerialPort-Assistant && ls
        - name: MAKE proj
          run: cmake -G "Unix Makefiles" -DwxMathPlot_LIB_DIR=../wxMathPlot && make -j8
        
        
