name: C/C++ CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest 
        
        steps:
        - uses: actions/checkout@v2
        - name: INSTALL dependency
          run: sudo apt-get install libboost-all-dev wx3.0* libwxgtk3.0-dev tree
          
        - name: CLONE wxMathPlot
          run: cd $GITHUB_WORKSPACE/.. && git clone https://github.com/mkarmona/wxMathPlot.git
        - name: MAKE wxMathPlot
          run: cd $GITHUB_WORKSPACE/../wxMathPlot && cmake -G "Unix Makefiles" && make -j2
        - name: MAKE proj
          run: cmake -G "Unix Makefiles" -DwxMathPlot_LIB_DIR=../wxMathPlot -DwxMathPlot_INCLUDE_DIR=../wxMathPlot && make -j2
        - name: Hurry!
          run: echo I made it! It took me 4hrs!!!
        