name: C/C++ CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest 
        
        steps:
        - name: INSTALL dependency
          run: sudo apt-get install libboost-all-dev wx3.0* libwxgtk3.0-dev 
          
        - name: CLONE wxMathPlot
          run: cd $HOME && ls && git clone https://github.com/mkarmona/wxMathPlot.git
        - name: MAKE wxMathPlot
          run: cd wxMathPlot && ls && cmake -G "Unix Makefiles" && make -j2
        - name: LIST
          run: cd $GITHUB_WORKSPACE && ls
        - name: MAKE proj
          run: cmake -G "Unix Makefiles" -DwxMathPlot_LIB_DIR=../wxMathPlot && make -j2
        
        
